#!/bin/sh

case "$1" in
start)
echo "Starting init script for openvpn modules"
modprobe tun
echo 1 > /proc/sys/net/ipv4/ip_forward
sh /usr/startupscripts/firewall.sh
if grep -Fxq FINISHED $LOGFILE
then
	openvpn --config /etc/openvpn/server/server.conf
fi
;;
stop)
echo "Removing tun modules"
rmmod tun
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
