#!/bin/sh

case "$1" in
    start)
        echo "Loading I2C modules"
        modprobe i2c-dev
        modprobe i2c-bcm2835

        echo "Loading LCD module"
        lcd_load
        ;;
    stop)
        echo "Removing user modules"
        lcd_unload
        rmmod i2c-bcm2835
        rmmod i2c-dev
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
