#!/bin/sh

case "$1" in
    start)
        echo "Loading AESD LCD Utility"
        start-stop-daemon -S -n aesd_lcd_util -a /usr/bin/aesd_lcd_util -- -wd
        ;;
    stop)
        echo "Removing AESD LCD Utility"
        start-stop-daemon -K -n aesd_lcd_util
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0